version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: crm_db
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_pass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crm-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
  frontendapp:
    image: node:20
    container_name: crm-react-js
    working_dir: /app
    volumes:
      - ./frontendapp/frontendapp:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm run dev -- --host"
    stdin_open: true
    tty: true

  login:
    image: node:20
    container_name: login-api-express
    working_dir: /app
    volumes:
      - ./login:/app
      - express_node_modules:/app/node_modules
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: mysql://root:root123@mysql:3306/crm_db
      DB_HOST: mysql
      DB_USER: crm_user
      DB_PASSWORD: crm_pass
      DB_NAME: crm_db
      DB_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npm install && npm run dev"

volumes:
  dbdata:
  frontend_node_modules:
  express_node_modules:
